version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.2.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: swift test

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - swiftlint
      - build-and-test
